/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_lua_line = 2,
  sym_lua_directive = 3,
  sym_asm_directive = 4,
  sym_section_header = 5,
  sym_compiler_directive = 6,
  sym_block_comment = 7,
  sym_line_comment = 8,
  sym_invalid_label_definition = 9,
  sym_address_definition = 10,
  anon_sym_COLON = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_COMMA = 19,
  sym_register = 20,
  sym_number = 21,
  sym_decimal_value = 22,
  sym_type_cast = 23,
  aux_sym_unknown_line_token1 = 24,
  sym__newline = 25,
  sym_source_file = 26,
  sym_lua_section = 27,
  sym_lua_content = 28,
  sym_lua_chunk = 29,
  sym_asm_section = 30,
  sym_asm_directive_line = 31,
  sym__asm_line = 32,
  sym_section_header_line = 33,
  sym_compiler_directive_line = 34,
  sym_block_comment_line = 35,
  sym_line_comment_line = 36,
  sym_label_definition_line = 37,
  sym_invalid_label_definition_line = 38,
  sym_address_definition_line = 39,
  sym_label_definition = 40,
  sym_aa_command_line = 41,
  sym_aa_command = 42,
  sym_argument_list = 43,
  sym_operation_line = 44,
  sym_operation = 45,
  sym__atom = 46,
  sym_typed_number = 47,
  sym_empty_line = 48,
  sym_unknown_line = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_lua_content_repeat1 = 51,
  aux_sym_lua_chunk_repeat1 = 52,
  aux_sym_argument_list_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_lua_line] = "lua_line",
  [sym_lua_directive] = "lua_directive",
  [sym_asm_directive] = "asm_directive",
  [sym_section_header] = "section_header",
  [sym_compiler_directive] = "compiler_directive",
  [sym_block_comment] = "block_comment",
  [sym_line_comment] = "line_comment",
  [sym_invalid_label_definition] = "invalid_label_definition",
  [sym_address_definition] = "address_definition",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [sym_register] = "register",
  [sym_number] = "number",
  [sym_decimal_value] = "decimal_value",
  [sym_type_cast] = "type_cast",
  [aux_sym_unknown_line_token1] = "unknown_line_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_lua_section] = "lua_section",
  [sym_lua_content] = "lua_content",
  [sym_lua_chunk] = "lua_chunk",
  [sym_asm_section] = "asm_section",
  [sym_asm_directive_line] = "asm_directive_line",
  [sym__asm_line] = "_asm_line",
  [sym_section_header_line] = "section_header_line",
  [sym_compiler_directive_line] = "compiler_directive_line",
  [sym_block_comment_line] = "block_comment_line",
  [sym_line_comment_line] = "line_comment_line",
  [sym_label_definition_line] = "label_definition_line",
  [sym_invalid_label_definition_line] = "invalid_label_definition_line",
  [sym_address_definition_line] = "address_definition_line",
  [sym_label_definition] = "label_definition",
  [sym_aa_command_line] = "aa_command_line",
  [sym_aa_command] = "aa_command",
  [sym_argument_list] = "argument_list",
  [sym_operation_line] = "operation_line",
  [sym_operation] = "operation",
  [sym__atom] = "_atom",
  [sym_typed_number] = "typed_number",
  [sym_empty_line] = "empty_line",
  [sym_unknown_line] = "unknown_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_lua_content_repeat1] = "lua_content_repeat1",
  [aux_sym_lua_chunk_repeat1] = "lua_chunk_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_lua_line] = sym_lua_line,
  [sym_lua_directive] = sym_lua_directive,
  [sym_asm_directive] = sym_asm_directive,
  [sym_section_header] = sym_section_header,
  [sym_compiler_directive] = sym_compiler_directive,
  [sym_block_comment] = sym_block_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_invalid_label_definition] = sym_invalid_label_definition,
  [sym_address_definition] = sym_address_definition,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_register] = sym_register,
  [sym_number] = sym_number,
  [sym_decimal_value] = sym_decimal_value,
  [sym_type_cast] = sym_type_cast,
  [aux_sym_unknown_line_token1] = aux_sym_unknown_line_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_lua_section] = sym_lua_section,
  [sym_lua_content] = sym_lua_content,
  [sym_lua_chunk] = sym_lua_chunk,
  [sym_asm_section] = sym_asm_section,
  [sym_asm_directive_line] = sym_asm_directive_line,
  [sym__asm_line] = sym__asm_line,
  [sym_section_header_line] = sym_section_header_line,
  [sym_compiler_directive_line] = sym_compiler_directive_line,
  [sym_block_comment_line] = sym_block_comment_line,
  [sym_line_comment_line] = sym_line_comment_line,
  [sym_label_definition_line] = sym_label_definition_line,
  [sym_invalid_label_definition_line] = sym_invalid_label_definition_line,
  [sym_address_definition_line] = sym_address_definition_line,
  [sym_label_definition] = sym_label_definition,
  [sym_aa_command_line] = sym_aa_command_line,
  [sym_aa_command] = sym_aa_command,
  [sym_argument_list] = sym_argument_list,
  [sym_operation_line] = sym_operation_line,
  [sym_operation] = sym_operation,
  [sym__atom] = sym__atom,
  [sym_typed_number] = sym_typed_number,
  [sym_empty_line] = sym_empty_line,
  [sym_unknown_line] = sym_unknown_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_lua_content_repeat1] = aux_sym_lua_content_repeat1,
  [aux_sym_lua_chunk_repeat1] = aux_sym_lua_chunk_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_line] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_compiler_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_invalid_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_address_definition] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_value] = {
    .visible = true,
    .named = true,
  },
  [sym_type_cast] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unknown_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_content] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_section] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym__asm_line] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_compiler_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition_line] = {
    .visible = true,
    .named = true,
  },
  [sym_invalid_label_definition_line] = {
    .visible = true,
    .named = true,
  },
  [sym_address_definition_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_aa_command_line] = {
    .visible = true,
    .named = true,
  },
  [sym_aa_command] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_operation_line] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_typed_number] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lua_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lua_chunk_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_content, 2},
  [2] =
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 17,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 25,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(63);
      ADVANCE_MAP(
        '\n', 186,
        '\r', 1,
        '#', 163,
        '$', 148,
        '(', 92,
        ')', 94,
        '*', 103,
        '+', 98,
        ',', 104,
        '-', 101,
        '.', 146,
        '/', 9,
        '0', 116,
        ':', 91,
        '?', 149,
        '[', 95,
        ']', 96,
        '{', 4,
        0x17f, 176,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(141);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(143);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(144);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(145);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(132);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(135);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(126);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(142);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(134);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(134);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(134);
      if (lookahead == 'F' ||
          lookahead == 'G' ||
          lookahead == 'f' ||
          lookahead == 'g') ADVANCE(136);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('H' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'w')) ADVANCE(149);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(185);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(186);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 186,
        '\r', 1,
        '#', 22,
        '$', 148,
        '(', 28,
        ')', 94,
        '*', 103,
        '+', 99,
        ',', 104,
        '-', 102,
        '.', 147,
        '/', 9,
        '0', 118,
        ':', 91,
        '[', 95,
        ']', 96,
        0x17f, 47,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(141);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(143);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(144);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(145);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(132);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(135);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(126);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(142);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(134);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(134);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(134);
      if (lookahead == 'F' ||
          lookahead == 'G' ||
          lookahead == 'f' ||
          lookahead == 'g') ADVANCE(136);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(118);
      if (lookahead == '?' ||
          ('H' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'w')) ADVANCE(149);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(64);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(24);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == '$') ADVANCE(36);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '$') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == ')') ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(86);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(83);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(85);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(84);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(84);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(84);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(84);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == '}') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '}') ADVANCE(82);
      END_STATE();
    case 19:
      if (lookahead == '}') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != '{') ADVANCE(87);
      END_STATE();
    case 22:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 23:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 24:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(15);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(16);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 28:
      ADVANCE_MAP(
        'B', 54,
        'b', 54,
        'D', 43,
        'd', 43,
        'F', 38,
        'f', 38,
        'I', 41,
        'i', 41,
        'Q', 53,
        'q', 53,
        'W', 44,
        'w', 44,
      );
      END_STATE();
    case 29:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 32:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 35:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 37:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 38:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 40:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 43:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(52);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 46:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 47:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(105);
      END_STATE();
    case 48:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(40);
      END_STATE();
    case 49:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(27);
      END_STATE();
    case 50:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(33);
      END_STATE();
    case 51:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(8);
      END_STATE();
    case 52:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 53:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(44);
      END_STATE();
    case 54:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(50);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 59:
      if (eof) ADVANCE(63);
      ADVANCE_MAP(
        '\n', 186,
        '\r', 1,
        '#', 22,
        '$', 148,
        '(', 93,
        ')', 94,
        '*', 103,
        '+', 97,
        ',', 104,
        '-', 100,
        '/', 9,
        '0', 113,
        ':', 91,
        '[', 95,
        ']', 96,
        '{', 7,
        0x17f, 47,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(141);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(143);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(144);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(145);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(132);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(135);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(126);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(142);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(134);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(134);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(134);
      if (lookahead == 'F' ||
          lookahead == 'G' ||
          lookahead == 'f' ||
          lookahead == 'g') ADVANCE(136);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(115);
      if (lookahead == '.' ||
          lookahead == '?' ||
          ('H' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'w')) ADVANCE(149);
      END_STATE();
    case 60:
      if (eof) ADVANCE(63);
      if (lookahead == '\n') ADVANCE(186);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '[') ADVANCE(161);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (lookahead == '.' ||
          lookahead == '?') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(151);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(185);
      END_STATE();
    case 61:
      if (eof) ADVANCE(63);
      if (lookahead == '\n') ADVANCE(186);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(72);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 62:
      if (eof) ADVANCE(63);
      if (lookahead == '[') ADVANCE(32);
      if (lookahead == '{') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_lua_line);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '$') ADVANCE(70);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '[') ADVANCE(72);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ']') ADVANCE(83);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '}') ADVANCE(82);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(71);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(78);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(75);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(74);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(77);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(67);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(73);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(68);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(69);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(76);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(69);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_lua_directive);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_asm_directive);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_compiler_directive);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_invalid_label_definition);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_address_definition);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_address_definition);
      if (lookahead == ':') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_address_definition);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      ADVANCE_MAP(
        'B', 181,
        'b', 181,
        'D', 172,
        'd', 172,
        'F', 170,
        'f', 170,
        'I', 171,
        'i', 171,
        'Q', 180,
        'q', 180,
        'W', 173,
        'w', 173,
      );
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      ADVANCE_MAP(
        'B', 54,
        'b', 54,
        'D', 43,
        'd', 43,
        'F', 38,
        'f', 38,
        'I', 41,
        'i', 41,
        'Q', 53,
        'q', 53,
        'W', 44,
        'w', 44,
      );
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '.') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '.') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(105);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'i' ||
          lookahead == 'p') ADVANCE(105);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'B' ||
          lookahead == 'D' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'w') ADVANCE(105);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'B' ||
          lookahead == 'D' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'w') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(108);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == '.') ADVANCE(121);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == '.') ADVANCE(121);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == '.') ADVANCE(123);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == '.') ADVANCE(123);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_decimal_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_decimal_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_type_cast);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '1', 109,
        'A', 137,
        'a', 137,
        'B', 140,
        'b', 140,
        'C', 137,
        'c', 137,
        'D', 139,
        'd', 139,
        'I', 135,
        'i', 135,
        'S', 138,
        's', 138,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('E' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('e' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(106);
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(162);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'A', 137,
        'a', 137,
        'B', 140,
        'b', 140,
        'C', 137,
        'c', 137,
        'D', 139,
        'd', 139,
        'I', 135,
        'i', 135,
        'S', 107,
        's', 107,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('E' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('e' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(127);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(133);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'i' ||
          lookahead == 'p') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'X' ||
          lookahead == 'i' ||
          lookahead == 'x') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'X' ||
          lookahead == 'p' ||
          lookahead == 'x') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H' ||
          lookahead == 'L' ||
          lookahead == 'X' ||
          lookahead == 'h' ||
          lookahead == 'l' ||
          lookahead == 'x') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'S' ||
          lookahead == 'i' ||
          lookahead == 'p' ||
          lookahead == 's') ADVANCE(105);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 105,
        'L', 105,
        'P', 105,
        'X', 105,
        'h', 105,
        'l', 105,
        'p', 105,
        'x', 105,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 105,
        'L', 105,
        'S', 105,
        'X', 105,
        'h', 105,
        'l', 105,
        's', 105,
        'x', 105,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 105,
        'I', 105,
        'L', 105,
        'S', 105,
        'X', 105,
        'h', 105,
        'i', 105,
        'l', 105,
        's', 105,
        'x', 105,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ')') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == ']') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(155);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(159);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(162);
      if (lookahead == '/' ||
          lookahead == '{') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(182);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(179);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(185);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 60},
  [2] = {.lex_state = 60},
  [3] = {.lex_state = 60},
  [4] = {.lex_state = 60},
  [5] = {.lex_state = 60},
  [6] = {.lex_state = 59},
  [7] = {.lex_state = 59},
  [8] = {.lex_state = 59},
  [9] = {.lex_state = 59},
  [10] = {.lex_state = 59},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 59},
  [13] = {.lex_state = 59},
  [14] = {.lex_state = 61},
  [15] = {.lex_state = 60},
  [16] = {.lex_state = 60},
  [17] = {.lex_state = 60},
  [18] = {.lex_state = 60},
  [19] = {.lex_state = 60},
  [20] = {.lex_state = 60},
  [21] = {.lex_state = 60},
  [22] = {.lex_state = 60},
  [23] = {.lex_state = 60},
  [24] = {.lex_state = 60},
  [25] = {.lex_state = 60},
  [26] = {.lex_state = 60},
  [27] = {.lex_state = 60},
  [28] = {.lex_state = 60},
  [29] = {.lex_state = 60},
  [30] = {.lex_state = 60},
  [31] = {.lex_state = 61},
  [32] = {.lex_state = 61},
  [33] = {.lex_state = 61},
  [34] = {.lex_state = 61},
  [35] = {.lex_state = 62},
  [36] = {.lex_state = 62},
  [37] = {.lex_state = 62},
  [38] = {.lex_state = 62},
  [39] = {.lex_state = 61},
  [40] = {.lex_state = 59},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 62},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 59},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_lua_directive] = ACTIONS(1),
    [sym_asm_directive] = ACTIONS(1),
    [sym_compiler_directive] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_decimal_value] = ACTIONS(1),
    [sym_type_cast] = ACTIONS(1),
    [aux_sym_unknown_line_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym_lua_section] = STATE(55),
    [sym__asm_line] = STATE(2),
    [sym_section_header_line] = STATE(2),
    [sym_compiler_directive_line] = STATE(2),
    [sym_block_comment_line] = STATE(2),
    [sym_line_comment_line] = STATE(2),
    [sym_label_definition_line] = STATE(2),
    [sym_invalid_label_definition_line] = STATE(2),
    [sym_address_definition_line] = STATE(2),
    [sym_label_definition] = STATE(41),
    [sym_aa_command_line] = STATE(2),
    [sym_aa_command] = STATE(47),
    [sym_operation_line] = STATE(2),
    [sym_operation] = STATE(45),
    [sym_empty_line] = STATE(2),
    [sym_unknown_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_invalid_label_definition] = ACTIONS(17),
    [sym_address_definition] = ACTIONS(19),
    [aux_sym_unknown_line_token1] = ACTIONS(21),
    [sym__newline] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_lua_section] = STATE(59),
    [sym__asm_line] = STATE(5),
    [sym_section_header_line] = STATE(5),
    [sym_compiler_directive_line] = STATE(5),
    [sym_block_comment_line] = STATE(5),
    [sym_line_comment_line] = STATE(5),
    [sym_label_definition_line] = STATE(5),
    [sym_invalid_label_definition_line] = STATE(5),
    [sym_address_definition_line] = STATE(5),
    [sym_label_definition] = STATE(41),
    [sym_aa_command_line] = STATE(5),
    [sym_aa_command] = STATE(47),
    [sym_operation_line] = STATE(5),
    [sym_operation] = STATE(45),
    [sym_empty_line] = STATE(5),
    [sym_unknown_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_invalid_label_definition] = ACTIONS(17),
    [sym_address_definition] = ACTIONS(19),
    [aux_sym_unknown_line_token1] = ACTIONS(21),
    [sym__newline] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_lua_section] = STATE(66),
    [sym__asm_line] = STATE(4),
    [sym_section_header_line] = STATE(4),
    [sym_compiler_directive_line] = STATE(4),
    [sym_block_comment_line] = STATE(4),
    [sym_line_comment_line] = STATE(4),
    [sym_label_definition_line] = STATE(4),
    [sym_invalid_label_definition_line] = STATE(4),
    [sym_address_definition_line] = STATE(4),
    [sym_label_definition] = STATE(41),
    [sym_aa_command_line] = STATE(4),
    [sym_aa_command] = STATE(47),
    [sym_operation_line] = STATE(4),
    [sym_operation] = STATE(45),
    [sym_empty_line] = STATE(4),
    [sym_unknown_line] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_invalid_label_definition] = ACTIONS(17),
    [sym_address_definition] = ACTIONS(19),
    [aux_sym_unknown_line_token1] = ACTIONS(21),
    [sym__newline] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_lua_section] = STATE(65),
    [sym__asm_line] = STATE(5),
    [sym_section_header_line] = STATE(5),
    [sym_compiler_directive_line] = STATE(5),
    [sym_block_comment_line] = STATE(5),
    [sym_line_comment_line] = STATE(5),
    [sym_label_definition_line] = STATE(5),
    [sym_invalid_label_definition_line] = STATE(5),
    [sym_address_definition_line] = STATE(5),
    [sym_label_definition] = STATE(41),
    [sym_aa_command_line] = STATE(5),
    [sym_aa_command] = STATE(47),
    [sym_operation_line] = STATE(5),
    [sym_operation] = STATE(45),
    [sym_empty_line] = STATE(5),
    [sym_unknown_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_invalid_label_definition] = ACTIONS(17),
    [sym_address_definition] = ACTIONS(19),
    [aux_sym_unknown_line_token1] = ACTIONS(21),
    [sym__newline] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(36), 1,
      sym_section_header,
    ACTIONS(39), 1,
      sym_compiler_directive,
    ACTIONS(42), 1,
      sym_block_comment,
    ACTIONS(45), 1,
      sym_line_comment,
    ACTIONS(48), 1,
      sym_invalid_label_definition,
    ACTIONS(51), 1,
      sym_address_definition,
    ACTIONS(54), 1,
      aux_sym_unknown_line_token1,
    ACTIONS(57), 1,
      sym__newline,
    STATE(41), 1,
      sym_label_definition,
    STATE(45), 1,
      sym_operation,
    STATE(47), 1,
      sym_aa_command,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_lua_directive,
    STATE(5), 13,
      sym__asm_line,
      sym_section_header_line,
      sym_compiler_directive_line,
      sym_block_comment_line,
      sym_line_comment_line,
      sym_label_definition_line,
      sym_invalid_label_definition_line,
      sym_address_definition_line,
      sym_aa_command_line,
      sym_operation_line,
      sym_empty_line,
      sym_unknown_line,
      aux_sym_source_file_repeat1,
  [56] = 7,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_COLON,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_type_cast,
    ACTIONS(62), 2,
      sym_line_comment,
      sym__newline,
    STATE(8), 3,
      sym__atom,
      sym_typed_number,
      aux_sym_argument_list_repeat1,
    ACTIONS(68), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
  [88] = 5,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(80), 1,
      sym_type_cast,
    ACTIONS(75), 3,
      sym_line_comment,
      anon_sym_RPAREN,
      sym__newline,
    STATE(7), 3,
      sym__atom,
      sym_typed_number,
      aux_sym_argument_list_repeat1,
    ACTIONS(77), 9,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
  [116] = 5,
    ACTIONS(70), 1,
      sym_type_cast,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(85), 2,
      sym_line_comment,
      sym__newline,
    STATE(7), 3,
      sym__atom,
      sym_typed_number,
      aux_sym_argument_list_repeat1,
    ACTIONS(87), 9,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
  [143] = 6,
    ACTIONS(70), 1,
      sym_type_cast,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_argument_list,
    STATE(10), 3,
      sym__atom,
      sym_typed_number,
      aux_sym_argument_list_repeat1,
    ACTIONS(91), 9,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
  [172] = 5,
    ACTIONS(70), 1,
      sym_type_cast,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(7), 3,
      sym__atom,
      sym_typed_number,
      aux_sym_argument_list_repeat1,
    ACTIONS(87), 9,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
  [198] = 3,
    ACTIONS(101), 1,
      sym_decimal_value,
    ACTIONS(97), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number,
      sym_identifier,
    ACTIONS(99), 10,
      sym_line_comment,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_type_cast,
      sym__newline,
  [220] = 2,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(105), 13,
      sym_line_comment,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
      sym__newline,
  [239] = 3,
    ACTIONS(97), 1,
      sym_identifier,
    ACTIONS(107), 3,
      sym_block_comment,
      sym_line_comment,
      sym__newline,
    ACTIONS(99), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [260] = 12,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      sym_lua_line,
    ACTIONS(113), 1,
      sym_asm_directive,
    ACTIONS(115), 1,
      sym_section_header,
    ACTIONS(117), 1,
      sym__newline,
    STATE(3), 1,
      sym_asm_directive_line,
    STATE(31), 1,
      sym_section_header_line,
    STATE(35), 1,
      sym_lua_chunk,
    STATE(36), 1,
      aux_sym_lua_content_repeat1,
    STATE(40), 1,
      sym_lua_content,
    STATE(49), 1,
      sym_asm_section,
    STATE(32), 2,
      sym_empty_line,
      aux_sym_lua_chunk_repeat1,
  [298] = 2,
    ACTIONS(121), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [314] = 2,
    ACTIONS(125), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [330] = 2,
    ACTIONS(129), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [346] = 2,
    ACTIONS(133), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [362] = 2,
    ACTIONS(137), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [378] = 2,
    ACTIONS(141), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [394] = 2,
    ACTIONS(145), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [410] = 2,
    ACTIONS(149), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [426] = 2,
    ACTIONS(153), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [442] = 2,
    ACTIONS(157), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [458] = 2,
    ACTIONS(161), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [474] = 2,
    ACTIONS(165), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [490] = 2,
    ACTIONS(169), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [506] = 2,
    ACTIONS(173), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [522] = 2,
    ACTIONS(177), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [538] = 2,
    ACTIONS(181), 4,
      sym_compiler_directive,
      sym_address_definition,
      sym_identifier,
      aux_sym_unknown_line_token1,
    ACTIONS(179), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_invalid_label_definition,
      sym__newline,
  [554] = 6,
    ACTIONS(111), 1,
      sym_lua_line,
    ACTIONS(117), 1,
      sym__newline,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      sym_lua_chunk,
    ACTIONS(185), 2,
      sym_asm_directive,
      sym_section_header,
    STATE(32), 2,
      sym_empty_line,
      aux_sym_lua_chunk_repeat1,
  [575] = 5,
    ACTIONS(117), 1,
      sym__newline,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 1,
      sym_lua_line,
    ACTIONS(191), 2,
      sym_asm_directive,
      sym_section_header,
    STATE(33), 2,
      sym_empty_line,
      aux_sym_lua_chunk_repeat1,
  [593] = 5,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 1,
      sym_lua_line,
    ACTIONS(200), 1,
      sym__newline,
    ACTIONS(198), 2,
      sym_asm_directive,
      sym_section_header,
    STATE(33), 2,
      sym_empty_line,
      aux_sym_lua_chunk_repeat1,
  [611] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 4,
      sym_lua_line,
      sym_asm_directive,
      sym_section_header,
      sym__newline,
  [621] = 4,
    ACTIONS(205), 1,
      sym_section_header,
    STATE(31), 1,
      sym_section_header_line,
    STATE(37), 1,
      aux_sym_lua_content_repeat1,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      sym_asm_directive,
  [635] = 4,
    ACTIONS(205), 1,
      sym_section_header,
    STATE(31), 1,
      sym_section_header_line,
    STATE(38), 1,
      aux_sym_lua_content_repeat1,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      sym_asm_directive,
  [649] = 4,
    ACTIONS(205), 1,
      sym_section_header,
    STATE(31), 1,
      sym_section_header_line,
    STATE(38), 1,
      aux_sym_lua_content_repeat1,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      sym_asm_directive,
  [663] = 4,
    ACTIONS(211), 1,
      sym_section_header,
    STATE(31), 1,
      sym_section_header_line,
    STATE(38), 1,
      aux_sym_lua_content_repeat1,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      sym_asm_directive,
  [677] = 2,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 4,
      sym_lua_line,
      sym_asm_directive,
      sym_section_header,
      sym__newline,
  [687] = 4,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
    ACTIONS(216), 1,
      sym_asm_directive,
    STATE(3), 1,
      sym_asm_directive_line,
    STATE(64), 1,
      sym_asm_section,
  [700] = 2,
    ACTIONS(220), 1,
      sym__newline,
    ACTIONS(218), 2,
      sym_block_comment,
      sym_line_comment,
  [708] = 1,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      sym_asm_directive,
      sym_section_header,
  [714] = 2,
    ACTIONS(222), 1,
      sym_line_comment,
    ACTIONS(224), 1,
      sym__newline,
  [721] = 1,
    ACTIONS(226), 2,
      sym_line_comment,
      sym__newline,
  [726] = 2,
    ACTIONS(228), 1,
      sym_line_comment,
    ACTIONS(230), 1,
      sym__newline,
  [733] = 1,
    ACTIONS(232), 2,
      sym_line_comment,
      sym__newline,
  [738] = 2,
    ACTIONS(234), 1,
      sym_line_comment,
    ACTIONS(236), 1,
      sym__newline,
  [745] = 1,
    ACTIONS(238), 1,
      sym__newline,
  [749] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [753] = 1,
    ACTIONS(242), 1,
      sym__newline,
  [757] = 1,
    ACTIONS(244), 1,
      sym__newline,
  [761] = 1,
    ACTIONS(246), 1,
      sym__newline,
  [765] = 1,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
  [769] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [773] = 1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [777] = 1,
    ACTIONS(252), 1,
      sym__newline,
  [781] = 1,
    ACTIONS(254), 1,
      sym__newline,
  [785] = 1,
    ACTIONS(256), 1,
      sym__newline,
  [789] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [793] = 1,
    ACTIONS(260), 1,
      sym__newline,
  [797] = 1,
    ACTIONS(262), 1,
      sym__newline,
  [801] = 1,
    ACTIONS(264), 1,
      sym__newline,
  [805] = 1,
    ACTIONS(266), 1,
      sym__newline,
  [809] = 1,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
  [813] = 1,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
  [817] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [821] = 1,
    ACTIONS(272), 1,
      sym__newline,
  [825] = 1,
    ACTIONS(274), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 88,
  [SMALL_STATE(8)] = 116,
  [SMALL_STATE(9)] = 143,
  [SMALL_STATE(10)] = 172,
  [SMALL_STATE(11)] = 198,
  [SMALL_STATE(12)] = 220,
  [SMALL_STATE(13)] = 239,
  [SMALL_STATE(14)] = 260,
  [SMALL_STATE(15)] = 298,
  [SMALL_STATE(16)] = 314,
  [SMALL_STATE(17)] = 330,
  [SMALL_STATE(18)] = 346,
  [SMALL_STATE(19)] = 362,
  [SMALL_STATE(20)] = 378,
  [SMALL_STATE(21)] = 394,
  [SMALL_STATE(22)] = 410,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 442,
  [SMALL_STATE(25)] = 458,
  [SMALL_STATE(26)] = 474,
  [SMALL_STATE(27)] = 490,
  [SMALL_STATE(28)] = 506,
  [SMALL_STATE(29)] = 522,
  [SMALL_STATE(30)] = 538,
  [SMALL_STATE(31)] = 554,
  [SMALL_STATE(32)] = 575,
  [SMALL_STATE(33)] = 593,
  [SMALL_STATE(34)] = 611,
  [SMALL_STATE(35)] = 621,
  [SMALL_STATE(36)] = 635,
  [SMALL_STATE(37)] = 649,
  [SMALL_STATE(38)] = 663,
  [SMALL_STATE(39)] = 677,
  [SMALL_STATE(40)] = 687,
  [SMALL_STATE(41)] = 700,
  [SMALL_STATE(42)] = 708,
  [SMALL_STATE(43)] = 714,
  [SMALL_STATE(44)] = 721,
  [SMALL_STATE(45)] = 726,
  [SMALL_STATE(46)] = 733,
  [SMALL_STATE(47)] = 738,
  [SMALL_STATE(48)] = 745,
  [SMALL_STATE(49)] = 749,
  [SMALL_STATE(50)] = 753,
  [SMALL_STATE(51)] = 757,
  [SMALL_STATE(52)] = 761,
  [SMALL_STATE(53)] = 765,
  [SMALL_STATE(54)] = 769,
  [SMALL_STATE(55)] = 773,
  [SMALL_STATE(56)] = 777,
  [SMALL_STATE(57)] = 781,
  [SMALL_STATE(58)] = 785,
  [SMALL_STATE(59)] = 789,
  [SMALL_STATE(60)] = 793,
  [SMALL_STATE(61)] = 797,
  [SMALL_STATE(62)] = 801,
  [SMALL_STATE(63)] = 805,
  [SMALL_STATE(64)] = 809,
  [SMALL_STATE(65)] = 813,
  [SMALL_STATE(66)] = 817,
  [SMALL_STATE(67)] = 821,
  [SMALL_STATE(68)] = 825,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typed_number, 2, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_number, 2, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 2, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition_line, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition_line, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment_line, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment_line, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header_line, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header_line, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compiler_directive_line, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compiler_directive_line, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command_line, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_aa_command_line, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment_line, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment_line, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invalid_label_definition_line, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_invalid_label_definition_line, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address_definition_line, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address_definition_line, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_line, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unknown_line, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_line, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation_line, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_line, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_line, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address_definition_line, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address_definition_line, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_directive_line, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asm_directive_line, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command_line, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_aa_command_line, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_line, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation_line, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition_line, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition_line, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lua_content_repeat1, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lua_content_repeat1, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_chunk, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_chunk, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lua_chunk_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lua_chunk_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_content, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_content, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 3, 0, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command, 3, 0, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command, 4, 0, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 4, 0, 2),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cea(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cea",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
