/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_lua_line = 2,
  sym_lua_directive = 3,
  sym_asm_directive = 4,
  sym_section_header = 5,
  sym_compiler_directive = 6,
  sym_block_comment = 7,
  sym_line_comment = 8,
  sym_address_definition = 9,
  anon_sym_COLON = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_PLUS = 15,
  anon_sym_DASH = 16,
  anon_sym_STAR = 17,
  anon_sym_COMMA = 18,
  sym_register = 19,
  sym_number = 20,
  sym_type_cast = 21,
  aux_sym_unknown_line_token1 = 22,
  sym__newline = 23,
  sym_source_file = 24,
  sym_lua_section = 25,
  sym_lua_content = 26,
  sym_asm_section = 27,
  sym_asm_directive_line = 28,
  sym__asm_line = 29,
  sym_section_header_line = 30,
  sym_compiler_directive_line = 31,
  sym_block_comment_line = 32,
  sym_line_comment_line = 33,
  sym_label_definition_line = 34,
  sym_address_definition_line = 35,
  sym_label_definition = 36,
  sym_aa_command_line = 37,
  sym_aa_command = 38,
  sym_argument_list = 39,
  sym_operation_line = 40,
  sym_operation = 41,
  sym__atom = 42,
  sym_empty_line = 43,
  sym_unknown_line = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_lua_content_repeat1 = 46,
  aux_sym_argument_list_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_lua_line] = "lua_line",
  [sym_lua_directive] = "lua_directive",
  [sym_asm_directive] = "asm_directive",
  [sym_section_header] = "section_header",
  [sym_compiler_directive] = "compiler_directive",
  [sym_block_comment] = "block_comment",
  [sym_line_comment] = "line_comment",
  [sym_address_definition] = "address_definition",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [sym_register] = "register",
  [sym_number] = "number",
  [sym_type_cast] = "type_cast",
  [aux_sym_unknown_line_token1] = "unknown_line_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_lua_section] = "lua_section",
  [sym_lua_content] = "lua_content",
  [sym_asm_section] = "asm_section",
  [sym_asm_directive_line] = "asm_directive_line",
  [sym__asm_line] = "_asm_line",
  [sym_section_header_line] = "section_header_line",
  [sym_compiler_directive_line] = "compiler_directive_line",
  [sym_block_comment_line] = "block_comment_line",
  [sym_line_comment_line] = "line_comment_line",
  [sym_label_definition_line] = "label_definition_line",
  [sym_address_definition_line] = "address_definition_line",
  [sym_label_definition] = "label_definition",
  [sym_aa_command_line] = "aa_command_line",
  [sym_aa_command] = "aa_command",
  [sym_argument_list] = "argument_list",
  [sym_operation_line] = "operation_line",
  [sym_operation] = "operation",
  [sym__atom] = "_atom",
  [sym_empty_line] = "empty_line",
  [sym_unknown_line] = "unknown_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_lua_content_repeat1] = "lua_content_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_lua_line] = sym_lua_line,
  [sym_lua_directive] = sym_lua_directive,
  [sym_asm_directive] = sym_asm_directive,
  [sym_section_header] = sym_section_header,
  [sym_compiler_directive] = sym_compiler_directive,
  [sym_block_comment] = sym_block_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_address_definition] = sym_address_definition,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_register] = sym_register,
  [sym_number] = sym_number,
  [sym_type_cast] = sym_type_cast,
  [aux_sym_unknown_line_token1] = aux_sym_unknown_line_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_lua_section] = sym_lua_section,
  [sym_lua_content] = sym_lua_content,
  [sym_asm_section] = sym_asm_section,
  [sym_asm_directive_line] = sym_asm_directive_line,
  [sym__asm_line] = sym__asm_line,
  [sym_section_header_line] = sym_section_header_line,
  [sym_compiler_directive_line] = sym_compiler_directive_line,
  [sym_block_comment_line] = sym_block_comment_line,
  [sym_line_comment_line] = sym_line_comment_line,
  [sym_label_definition_line] = sym_label_definition_line,
  [sym_address_definition_line] = sym_address_definition_line,
  [sym_label_definition] = sym_label_definition,
  [sym_aa_command_line] = sym_aa_command_line,
  [sym_aa_command] = sym_aa_command,
  [sym_argument_list] = sym_argument_list,
  [sym_operation_line] = sym_operation_line,
  [sym_operation] = sym_operation,
  [sym__atom] = sym__atom,
  [sym_empty_line] = sym_empty_line,
  [sym_unknown_line] = sym_unknown_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_lua_content_repeat1] = aux_sym_lua_content_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_line] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_compiler_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_address_definition] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_type_cast] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unknown_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_content] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_section] = {
    .visible = true,
    .named = true,
  },
  [sym_asm_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym__asm_line] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_compiler_directive_line] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition_line] = {
    .visible = true,
    .named = true,
  },
  [sym_address_definition_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_aa_command_line] = {
    .visible = true,
    .named = true,
  },
  [sym_aa_command] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_operation_line] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lua_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_content, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 25,
  [31] = 15,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '\n', 136,
        '\r', 1,
        '$', 105,
        '(', 70,
        ')', 72,
        '*', 77,
        '+', 75,
        ',', 78,
        '-', 76,
        '/', 7,
        '0', 85,
        ':', 69,
        '[', 73,
        ']', 74,
        '{', 3,
        0x17f, 133,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '.' ||
          lookahead == '?') ADVANCE(106);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(100);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(102);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(103);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(104);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(91);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(94);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(89);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(101);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(93);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(93);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(93);
      if (lookahead == 'F' ||
          lookahead == 'G' ||
          lookahead == 'f' ||
          lookahead == 'g') ADVANCE(95);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (('H' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'w')) ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(135);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(136);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(33);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(35);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '$') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == ')') ADVANCE(88);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(21);
      if (lookahead == 'w') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 22:
      if (lookahead == 'w') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == '}') ADVANCE(65);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(64);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(64);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(64);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(64);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(62);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == '}') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(27);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(28);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 36:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 37:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(79);
      END_STATE();
    case 38:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(36);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 40:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '\n', 136,
        '\r', 1,
        '$', 105,
        '(', 71,
        ')', 72,
        '*', 77,
        '+', 75,
        ',', 78,
        '-', 76,
        '/', 7,
        '0', 86,
        ':', 69,
        '[', 73,
        ']', 74,
        '{', 5,
        0x17f, 37,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(40);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(100);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(102);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(103);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(104);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(91);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(94);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(89);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(101);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(93);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(93);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(93);
      if (lookahead == 'F' ||
          lookahead == 'G' ||
          lookahead == 'f' ||
          lookahead == 'g') ADVANCE(95);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (lookahead == '.' ||
          lookahead == '?' ||
          ('H' <= lookahead && lookahead <= 'W') ||
          lookahead == '_' ||
          ('h' <= lookahead && lookahead <= 'w')) ADVANCE(106);
      END_STATE();
    case 41:
      if (eof) ADVANCE(43);
      if (lookahead == '\n') ADVANCE(136);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '[') ADVANCE(117);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(41);
      if (lookahead == '.' ||
          lookahead == '?') ADVANCE(106);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(135);
      END_STATE();
    case 42:
      if (eof) ADVANCE(43);
      if (lookahead == '\n') ADVANCE(136);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(52);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_lua_line);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '$') ADVANCE(50);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '[') ADVANCE(52);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ']') ADVANCE(63);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '}') ADVANCE(62);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(51);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(58);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(55);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(54);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(57);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(53);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(48);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(49);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(56);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(49);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_lua_directive);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_asm_directive);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_compiler_directive);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_address_definition);
      if (lookahead == ':') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_address_definition);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == 'b') ADVANCE(132);
      if (lookahead == 'd') ADVANCE(124);
      if (lookahead == 'f') ADVANCE(123);
      if (lookahead == 'q') ADVANCE(131);
      if (lookahead == 'w') ADVANCE(125);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == 'b') ADVANCE(23);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'q') ADVANCE(22);
      if (lookahead == 'w') ADVANCE(16);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'i' ||
          lookahead == 'p') ADVANCE(79);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'B' ||
          lookahead == 'D' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'w') ADVANCE(79);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'B' ||
          lookahead == 'D' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'w') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_type_cast);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '1', 83,
        'A', 96,
        'a', 96,
        'B', 99,
        'b', 99,
        'C', 96,
        'c', 96,
        'D', 98,
        'd', 98,
        'I', 94,
        'i', 94,
        'S', 97,
        's', 97,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('E' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('e' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(80);
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'A', 96,
        'a', 96,
        'B', 99,
        'b', 99,
        'C', 96,
        'c', 96,
        'D', 98,
        'd', 98,
        'I', 94,
        'i', 94,
        'S', 81,
        's', 81,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('E' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('e' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(90);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(92);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'i' ||
          lookahead == 'p') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'X' ||
          lookahead == 'i' ||
          lookahead == 'x') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'X' ||
          lookahead == 'p' ||
          lookahead == 'x') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H' ||
          lookahead == 'L' ||
          lookahead == 'X' ||
          lookahead == 'h' ||
          lookahead == 'l' ||
          lookahead == 'x') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'P' ||
          lookahead == 'S' ||
          lookahead == 'i' ||
          lookahead == 'p' ||
          lookahead == 's') ADVANCE(79);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 79,
        'L', 79,
        'P', 79,
        'X', 79,
        'h', 79,
        'l', 79,
        'p', 79,
        'x', 79,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 79,
        'L', 79,
        'S', 79,
        'X', 79,
        'h', 79,
        'l', 79,
        's', 79,
        'x', 79,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'H', 79,
        'I', 79,
        'L', 79,
        'S', 79,
        'X', 79,
        'h', 79,
        'i', 79,
        'l', 79,
        's', 79,
        'x', 79,
      );
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      if (lookahead == '$' ||
          lookahead == '.' ||
          lookahead == '?' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ')') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ']') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(111);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(115);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'a') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'b') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'd') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'e') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'l') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'l') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'o') ADVANCE(130);
      if (lookahead == 'w') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'o') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'o') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'r') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 't') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 't') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'u') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'w') ADVANCE(125);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'y') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_unknown_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(135);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 41},
  [2] = {.lex_state = 41},
  [3] = {.lex_state = 41},
  [4] = {.lex_state = 41},
  [5] = {.lex_state = 41},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 40},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 42},
  [13] = {.lex_state = 41},
  [14] = {.lex_state = 41},
  [15] = {.lex_state = 41},
  [16] = {.lex_state = 41},
  [17] = {.lex_state = 41},
  [18] = {.lex_state = 41},
  [19] = {.lex_state = 41},
  [20] = {.lex_state = 41},
  [21] = {.lex_state = 41},
  [22] = {.lex_state = 41},
  [23] = {.lex_state = 41},
  [24] = {.lex_state = 41},
  [25] = {.lex_state = 41},
  [26] = {.lex_state = 41},
  [27] = {.lex_state = 41},
  [28] = {.lex_state = 42},
  [29] = {.lex_state = 42},
  [30] = {.lex_state = 42},
  [31] = {.lex_state = 42},
  [32] = {.lex_state = 40},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 40},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_lua_directive] = ACTIONS(1),
    [sym_asm_directive] = ACTIONS(1),
    [sym_compiler_directive] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_type_cast] = ACTIONS(1),
    [aux_sym_unknown_line_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym_lua_section] = STATE(39),
    [sym__asm_line] = STATE(4),
    [sym_section_header_line] = STATE(4),
    [sym_compiler_directive_line] = STATE(4),
    [sym_block_comment_line] = STATE(4),
    [sym_line_comment_line] = STATE(4),
    [sym_label_definition_line] = STATE(4),
    [sym_address_definition_line] = STATE(4),
    [sym_label_definition] = STATE(37),
    [sym_aa_command_line] = STATE(4),
    [sym_aa_command] = STATE(35),
    [sym_operation_line] = STATE(4),
    [sym_operation] = STATE(34),
    [sym_empty_line] = STATE(4),
    [sym_unknown_line] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_address_definition] = ACTIONS(17),
    [aux_sym_unknown_line_token1] = ACTIONS(19),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym_lua_section] = STATE(51),
    [sym__asm_line] = STATE(3),
    [sym_section_header_line] = STATE(3),
    [sym_compiler_directive_line] = STATE(3),
    [sym_block_comment_line] = STATE(3),
    [sym_line_comment_line] = STATE(3),
    [sym_label_definition_line] = STATE(3),
    [sym_address_definition_line] = STATE(3),
    [sym_label_definition] = STATE(37),
    [sym_aa_command_line] = STATE(3),
    [sym_aa_command] = STATE(35),
    [sym_operation_line] = STATE(3),
    [sym_operation] = STATE(34),
    [sym_empty_line] = STATE(3),
    [sym_unknown_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_address_definition] = ACTIONS(17),
    [aux_sym_unknown_line_token1] = ACTIONS(19),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_lua_section] = STATE(55),
    [sym__asm_line] = STATE(5),
    [sym_section_header_line] = STATE(5),
    [sym_compiler_directive_line] = STATE(5),
    [sym_block_comment_line] = STATE(5),
    [sym_line_comment_line] = STATE(5),
    [sym_label_definition_line] = STATE(5),
    [sym_address_definition_line] = STATE(5),
    [sym_label_definition] = STATE(37),
    [sym_aa_command_line] = STATE(5),
    [sym_aa_command] = STATE(35),
    [sym_operation_line] = STATE(5),
    [sym_operation] = STATE(34),
    [sym_empty_line] = STATE(5),
    [sym_unknown_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_address_definition] = ACTIONS(17),
    [aux_sym_unknown_line_token1] = ACTIONS(19),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym_lua_section] = STATE(49),
    [sym__asm_line] = STATE(5),
    [sym_section_header_line] = STATE(5),
    [sym_compiler_directive_line] = STATE(5),
    [sym_block_comment_line] = STATE(5),
    [sym_line_comment_line] = STATE(5),
    [sym_label_definition_line] = STATE(5),
    [sym_address_definition_line] = STATE(5),
    [sym_label_definition] = STATE(37),
    [sym_aa_command_line] = STATE(5),
    [sym_aa_command] = STATE(35),
    [sym_operation_line] = STATE(5),
    [sym_operation] = STATE(34),
    [sym_empty_line] = STATE(5),
    [sym_unknown_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(5),
    [sym_lua_directive] = ACTIONS(7),
    [sym_section_header] = ACTIONS(9),
    [sym_compiler_directive] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(15),
    [sym_address_definition] = ACTIONS(17),
    [aux_sym_unknown_line_token1] = ACTIONS(19),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(5)] = {
    [sym__asm_line] = STATE(5),
    [sym_section_header_line] = STATE(5),
    [sym_compiler_directive_line] = STATE(5),
    [sym_block_comment_line] = STATE(5),
    [sym_line_comment_line] = STATE(5),
    [sym_label_definition_line] = STATE(5),
    [sym_address_definition_line] = STATE(5),
    [sym_label_definition] = STATE(37),
    [sym_aa_command_line] = STATE(5),
    [sym_aa_command] = STATE(35),
    [sym_operation_line] = STATE(5),
    [sym_operation] = STATE(34),
    [sym_empty_line] = STATE(5),
    [sym_unknown_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_lua_directive] = ACTIONS(29),
    [sym_section_header] = ACTIONS(34),
    [sym_compiler_directive] = ACTIONS(37),
    [sym_block_comment] = ACTIONS(40),
    [sym_line_comment] = ACTIONS(43),
    [sym_address_definition] = ACTIONS(46),
    [aux_sym_unknown_line_token1] = ACTIONS(49),
    [sym__newline] = ACTIONS(52),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_COLON,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 2,
      sym_line_comment,
      sym__newline,
    STATE(9), 2,
      sym__atom,
      aux_sym_argument_list_repeat1,
    ACTIONS(63), 9,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [29] = 4,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(7), 2,
      sym__atom,
      aux_sym_argument_list_repeat1,
    ACTIONS(68), 3,
      sym_line_comment,
      anon_sym_RPAREN,
      sym__newline,
    ACTIONS(70), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [54] = 5,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_argument_list,
    STATE(10), 2,
      sym__atom,
      aux_sym_argument_list_repeat1,
    ACTIONS(75), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [80] = 4,
    ACTIONS(79), 1,
      sym_identifier,
    ACTIONS(81), 2,
      sym_line_comment,
      sym__newline,
    STATE(7), 2,
      sym__atom,
      aux_sym_argument_list_repeat1,
    ACTIONS(83), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [104] = 4,
    ACTIONS(79), 1,
      sym_identifier,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(7), 2,
      sym__atom,
      aux_sym_argument_list_repeat1,
    ACTIONS(83), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [127] = 3,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 2,
      sym_line_comment,
      sym__newline,
    ACTIONS(91), 10,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      sym_register,
      sym_number,
      sym_type_cast,
  [147] = 9,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 1,
      sym_lua_line,
    ACTIONS(97), 1,
      sym_asm_directive,
    ACTIONS(99), 1,
      sym_section_header,
    ACTIONS(101), 1,
      sym__newline,
    STATE(2), 1,
      sym_asm_directive_line,
    STATE(32), 1,
      sym_lua_content,
    STATE(56), 1,
      sym_asm_section,
    STATE(28), 3,
      sym_section_header_line,
      sym_empty_line,
      aux_sym_lua_content_repeat1,
  [177] = 2,
    ACTIONS(105), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [192] = 2,
    ACTIONS(109), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [207] = 2,
    ACTIONS(113), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [222] = 2,
    ACTIONS(117), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [237] = 2,
    ACTIONS(121), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [252] = 2,
    ACTIONS(125), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [267] = 2,
    ACTIONS(129), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [282] = 2,
    ACTIONS(133), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [297] = 2,
    ACTIONS(137), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [312] = 2,
    ACTIONS(141), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [327] = 2,
    ACTIONS(145), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [342] = 2,
    ACTIONS(149), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [357] = 2,
    ACTIONS(153), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [372] = 2,
    ACTIONS(157), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [387] = 2,
    ACTIONS(161), 3,
      sym_compiler_directive,
      sym_address_definition,
      aux_sym_unknown_line_token1,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      sym_lua_directive,
      sym_section_header,
      sym_block_comment,
      sym_line_comment,
      sym_identifier,
      sym__newline,
  [402] = 6,
    ACTIONS(99), 1,
      sym_section_header,
    ACTIONS(101), 1,
      sym__newline,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 1,
      sym_lua_line,
    ACTIONS(167), 1,
      sym_asm_directive,
    STATE(29), 3,
      sym_section_header_line,
      sym_empty_line,
      aux_sym_lua_content_repeat1,
  [423] = 6,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      sym_lua_line,
    ACTIONS(174), 1,
      sym_asm_directive,
    ACTIONS(176), 1,
      sym_section_header,
    ACTIONS(179), 1,
      sym__newline,
    STATE(29), 3,
      sym_section_header_line,
      sym_empty_line,
      aux_sym_lua_content_repeat1,
  [444] = 2,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 4,
      sym_lua_line,
      sym_asm_directive,
      sym_section_header,
      sym__newline,
  [454] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 4,
      sym_lua_line,
      sym_asm_directive,
      sym_section_header,
      sym__newline,
  [464] = 4,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 1,
      sym_asm_directive,
    STATE(2), 1,
      sym_asm_directive_line,
    STATE(50), 1,
      sym_asm_section,
  [477] = 2,
    ACTIONS(186), 1,
      sym_line_comment,
    ACTIONS(188), 1,
      sym__newline,
  [484] = 2,
    ACTIONS(190), 1,
      sym_line_comment,
    ACTIONS(192), 1,
      sym__newline,
  [491] = 2,
    ACTIONS(194), 1,
      sym_line_comment,
    ACTIONS(196), 1,
      sym__newline,
  [498] = 1,
    ACTIONS(198), 2,
      sym_line_comment,
      sym__newline,
  [503] = 2,
    ACTIONS(200), 1,
      sym_line_comment,
    ACTIONS(202), 1,
      sym__newline,
  [510] = 1,
    ACTIONS(204), 2,
      sym_line_comment,
      sym__newline,
  [515] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [519] = 1,
    ACTIONS(206), 1,
      sym__newline,
  [523] = 1,
    ACTIONS(208), 1,
      sym__newline,
  [527] = 1,
    ACTIONS(210), 1,
      sym__newline,
  [531] = 1,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
  [535] = 1,
    ACTIONS(214), 1,
      sym__newline,
  [539] = 1,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
  [543] = 1,
    ACTIONS(218), 1,
      sym__newline,
  [547] = 1,
    ACTIONS(220), 1,
      sym__newline,
  [551] = 1,
    ACTIONS(222), 1,
      sym__newline,
  [555] = 1,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
  [559] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [563] = 1,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [567] = 1,
    ACTIONS(228), 1,
      sym__newline,
  [571] = 1,
    ACTIONS(230), 1,
      sym__newline,
  [575] = 1,
    ACTIONS(232), 1,
      sym__newline,
  [579] = 1,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
  [583] = 1,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
  [587] = 1,
    ACTIONS(238), 1,
      sym__newline,
  [591] = 1,
    ACTIONS(240), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 29,
  [SMALL_STATE(8)] = 54,
  [SMALL_STATE(9)] = 80,
  [SMALL_STATE(10)] = 104,
  [SMALL_STATE(11)] = 127,
  [SMALL_STATE(12)] = 147,
  [SMALL_STATE(13)] = 177,
  [SMALL_STATE(14)] = 192,
  [SMALL_STATE(15)] = 207,
  [SMALL_STATE(16)] = 222,
  [SMALL_STATE(17)] = 237,
  [SMALL_STATE(18)] = 252,
  [SMALL_STATE(19)] = 267,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 297,
  [SMALL_STATE(22)] = 312,
  [SMALL_STATE(23)] = 327,
  [SMALL_STATE(24)] = 342,
  [SMALL_STATE(25)] = 357,
  [SMALL_STATE(26)] = 372,
  [SMALL_STATE(27)] = 387,
  [SMALL_STATE(28)] = 402,
  [SMALL_STATE(29)] = 423,
  [SMALL_STATE(30)] = 444,
  [SMALL_STATE(31)] = 454,
  [SMALL_STATE(32)] = 464,
  [SMALL_STATE(33)] = 477,
  [SMALL_STATE(34)] = 484,
  [SMALL_STATE(35)] = 491,
  [SMALL_STATE(36)] = 498,
  [SMALL_STATE(37)] = 503,
  [SMALL_STATE(38)] = 510,
  [SMALL_STATE(39)] = 515,
  [SMALL_STATE(40)] = 519,
  [SMALL_STATE(41)] = 523,
  [SMALL_STATE(42)] = 527,
  [SMALL_STATE(43)] = 531,
  [SMALL_STATE(44)] = 535,
  [SMALL_STATE(45)] = 539,
  [SMALL_STATE(46)] = 543,
  [SMALL_STATE(47)] = 547,
  [SMALL_STATE(48)] = 551,
  [SMALL_STATE(49)] = 555,
  [SMALL_STATE(50)] = 559,
  [SMALL_STATE(51)] = 563,
  [SMALL_STATE(52)] = 567,
  [SMALL_STATE(53)] = 571,
  [SMALL_STATE(54)] = 575,
  [SMALL_STATE(55)] = 579,
  [SMALL_STATE(56)] = 583,
  [SMALL_STATE(57)] = 587,
  [SMALL_STATE(58)] = 591,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 2, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_directive_line, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asm_directive_line, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment_line, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment_line, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header_line, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header_line, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compiler_directive_line, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compiler_directive_line, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition_line, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition_line, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment_line, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment_line, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address_definition_line, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address_definition_line, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_line, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unknown_line, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command_line, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_aa_command_line, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_line, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation_line, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition_line, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition_line, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address_definition_line, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_address_definition_line, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_line, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_line, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_line, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation_line, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command_line, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_aa_command_line, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_content, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_content, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_content_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 3, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command, 3, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aa_command, 4, 0, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [216] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 4, 0, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asm_section, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_section, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cea(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cea",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
